### PR TITLE
Upgrade Alpine image to 3.5

### PR DESCRIPTION
**Pull request by andypost**
New release is out https://alpinelinux.org/posts/Alpine-3.5.0-released.html

### CODE REVIEW

**Comment by mhart** [comment]
Yeah I tweeted about this the other day: https://twitter.com/hichaelmart/status/811953434136088577

I'll leave all existing images on 3.4 for now so there are no breaking changes – possibly when Node.js v8.x comes out I'll upgrade

**Comment by jamesvl** [comment]
Any chance you'd be willing to have a separate branch or something for Alpine 3.5? Node versions aside (you've got that covered), 3.5 offers libsass, which will save a lot of compile time when using node-sass.

**Comment by mhart** [comment]
@jamesvl no – no chance I'll do a separate branch, it's too much overhead (already 10 builds to manage – that would make it 20)

I might consider doing it for the next Node.js v7 release though – considering it's not an LTS release, users should be prepared for potentially breaking changes.

Would that be useful?

**Comment by jamesvl** [comment]
Totally agree - 20 builds is a lot to manage. I can wait until a Nodejs 7 release (if you go that route); fortunately, Alpine 3.5 makes it easy to use nodejs and libsass from APKs now too, so that will hold me over. Thanks!

**Comment by mhart** [comment]
@jamesvl – I've updated the latest Node.js v7.5.0 to Alpine 3.5 – will continue that going forward on v7 and v8. Will also consider it for the next minor (not patch) bump in v4 or v6 – if one occurs.

**Pull request closed without merging**
